SunbiHR/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Asn1.Cms;
using SunbiHR.DBContext;
using SunbiHR.Extensions;
using SunbiHR.Helper;
using SunbiHR.Models.Entity;
using SunbiHR.Models.Entity.EmployeeInfo;
using SunbiHR.Models.Entity.ProjectInfo;
using SunbiHR.Models.Entity.TaskInfo;
using SunbiHR.Models.Entity.UserDetails;
using SunbiHR.Models.Enum;
using SunbiHR.ViewModel;

namespace SunbiHR.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly SunbiDBContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ILogger<ReportController> _logger;

        public ReportController(
            SunbiDBContext context, 
            UserManager<ApplicationUser> userManager,
            ILogger<ReportController> logger)
        {
            _context = context;
            this.userManager = userManager;
            _logger = logger;
        }

        // GET: Project
        public async Task<IActionResult> Index(DateTime? fromDate, DateTime? toDate, ReportViewModel reportViewModel)
        {
            fromDate = fromDate.HasValue ? fromDate : DateTime.Now;
            toDate = toDate.HasValue ? toDate : DateTime.Now;
            InitCommon(reportViewModel);
            ViewData["fromDate"] = fromDate.Value.Date.ToString("yyyy-MM-dd");
            ViewData["toDate"] = toDate.Value.Date.ToString("yyyy-MM-dd");
            var employeeDailyReportList = _context.EmployeeDailyReport
                .Where(x => x.Deleted_Status == false)
                .Include(e => e.ApplicationUser)
                .Include(x => x.EmployeeInformation).AsNoTracking().AsQueryable();
            employeeDailyReportList = employeeDailyReportList.Where(x => x.CreatedOn.Date >= fromDate.Value.Date && x.CreatedOn.Date <= toDate.Value.Date);

            if (!User.IsInRole("Administrator"))
            {
                employeeDailyReportList = employeeDailyReportList.Where(x => x.EmployeeId == User.GetEmployeeId());
            }
            if (!string.IsNullOrEmpty(reportViewModel?.EmployeeId))
            {
                employeeDailyReportList = employeeDailyReportList.Where(x => x.EmployeeId == reportViewModel.EmployeeId);

            }      
            return View(await employeeDailyReportList.ToListAsync());
        }

        // GET: Project/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employeeDailyReport = await _context.EmployeeDailyReport
                .Include(e => e.ApplicationUser)
                .Include(x => x.EmployeeInformation)
                .Include(x => x.DailyReportProject)
                .ThenInclude(x=>x.ProjectInformation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employeeDailyReport == null)
            {
                return NotFound();
            }

            return View(employeeDailyReport);
        }

        public IActionResult Create()
        {
            var reportViewModel = new ReportViewModel();
            reportViewModel.Title = "Daily Report";
            reportViewModel.CreatedOn= DateTime.Now;
            InitCommon(reportViewModel);
            return View(reportViewModel);
        }

        private void InitCommon(ReportViewModel reportViewModel)
        {
            ViewData["EmployeeId"] = new SelectList(_context.EmployeeInformation, "Id", "Fullname", reportViewModel?.EmployeeId);
            //ViewData["Projects"] = new MultiSelectList(_context.ProjectInformation, "Id", "Title", reportViewModel?.DailyReportProject?.Select(x => x.ProjectId).ToArray());
            if (User.IsInRole("SuperAdmin"))
            {
                ViewData["Projects"] = new MultiSelectList(_context.ProjectInformation, "Id", "Title", reportViewModel?.DailyReportProject?.Select(x => x.ProjectId).ToArray());
            }
            else
            {
                ViewData["Projects"] = new MultiSelectList(_context.EmployeeProject.Where(x => x.EmployeeId == User.GetEmployeeId()).Include(x => x.ProjectInformation)
                                        .Select(x => x.ProjectInformation).ToList(), "Id", "Title", reportViewModel?.DailyReportProject?.Select(x => x.ProjectId).ToArray());
            } 

        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReportViewModel reportViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var employeeDailyReport = new EmployeeDailyReport();
                    SetValuesFromViewModel(reportViewModel, employeeDailyReport);
                    employeeDailyReport.Id = Guid.NewGuid().ToString();
                    employeeDailyReport.CreatedById = User.GetUserId();
                    //employeeDailyReport.CreatedOn = DateTime.Now;
                    //employeeDailyReport.LastModifiedDate = DateTime.Now;
                    //employeeDailyReport.ModifiedTimes = 0;
                    //employeeDailyReport.Record_Status = Models.Enum.Record_Status.Active;
                    //employeeDailyReport.Deleted_Status = false;
                    employeeDailyReport.EmployeeId = User.GetEmployeeId();
                    
                    _context.Add(employeeDailyReport);
                    await _context.CommitAsync();
                    this.Notify("Daily Report Created Successfully", "Notice");
                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {
                this.Notify("Error while creating daily report.", ExceptionHelper.GetMsg(ex), "error");
                _logger.LogError(ex, ExceptionHelper.GetMsg(ex));
            }

            InitCommon(reportViewModel);
            return View(reportViewModel);
        }

        private void SetValuesFromViewModel(ReportViewModel reportViewModel, EmployeeDailyReport employeeDailyReport)
        {
            employeeDailyReport.Title = reportViewModel.Title;
            employeeDailyReport.Description = reportViewModel.Description;
            var oldIds = employeeDailyReport.DailyReportProject.Where(x => !x.Deleted_Status)
                .Select(x => x.ProjectId).ToArray();//1,2,3
            var newlyAddedIds = reportViewModel.Projects.Except(oldIds);//4
            var removedIds = oldIds.Except(reportViewModel.Projects);//1
            //change status of removed project
            foreach (var item in removedIds)
            {
                var removedProject = employeeDailyReport.DailyReportProject.FirstOrDefault(x => x.ProjectId == item);
                if (removedProject != null)
                {
                    removedProject.Deleted_Status = true;
                    _context.DailyReportProject.Update(removedProject);
                }
            }
            //add new assigned project
            foreach (var item in newlyAddedIds)
            {
                employeeDailyReport.DailyReportProject.Add(new DailyReportProject()
                {
                    Id=Guid.NewGuid().ToString(),
                    ProjectId = item,
                    CreatedById = User.GetUserId(),
                });
            }
        }

        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employeeDailyReport = await _context.EmployeeDailyReport
                .Include(x => x.EmployeeInformation)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (employeeDailyReport == null)
            {
                return NotFound();
            }
            var reportViewModel = new ReportViewModel()
            {
                Id = employeeDailyReport.Id,
                Description = employeeDailyReport.Description,
                Title = employeeDailyReport.Title,
                //EmployeeId=employeeDailyReport.EmployeeId
            };
            InitCommon(reportViewModel);
            return View(reportViewModel);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, ReportViewModel reportViewModel)
        {
            if (id != reportViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (id == null)
                    {
                        return NotFound();
                    }

                    var OldData = await _context.EmployeeDailyReport.Include(x=>x.DailyReportProject).FirstOrDefaultAsync(x=>x.Id== id);
                    if (OldData == null)
                    {
                        return NotFound();
                    }
                    OldData.LastModifiedDate = DateTime.Now;
                    OldData.ModifiedTimes += 1;
                    SetValuesFromViewModel(reportViewModel, OldData);
                    _context.Update(OldData);
                    await _context.CommitAsync();

SunbiHR/Views/Report/Create.cshtml
@model SunbiHR.ViewModel.ReportViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Report</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            @Html.EditorForModel()
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $(".datepicker").each(function () {
                $(this).datepicker();
            });
        });
        $('#ProjectId').on("change", function (event) {
            var val = $("#ProjectId option:selected").val();
            if (val=="") {
                return;
            }
        $.ajax({
            url: "@Url.Action("GetMilestoneByProjectId", "Milestone")",
            data: {id:val},
            type: 'GET',
            cache: false,
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            success: function (result) {
                if (result.status) {
                    var dbSelect = $('#MilestoneId');
                    dbSelect.empty();
                    dbSelect.append("<option value=''>Select an option</option>");

                    //dbSelect.select2('data', null);

                    //$("#select_with_data").html('').trigger('change');//.select2({
                    //    data: result.DataList
                    //});
                    $.each(result.dataList, function (key, value) {
                        dbSelect.append("<option value='" + value.id + "'>" + value.text + "</option>");

                    });

                    dbSelect.trigger('change');
                }

            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(thrownError);
            }
        });
    });
    </script>
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SunbiHR/Views/Report/Delete.cshtml
@model SunbiHR.Models.Entity.EmployeeInfo.EmployeeDailyReport

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Report</h4>
    <hr />
    @Html.DisplayForModel()

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SunbiHR/Views/Report/Details.cshtml
@model SunbiHR.Models.Entity.EmployeeInfo.EmployeeDailyReport
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4> Report</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            @Html.DisplayForModel()
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SunbiHR/Views/Report/Edit.cshtml
@model SunbiHR.ViewModel.ReportViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Report</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            @Html.EditorForModel()
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    <script>
        $('#ProjectId').on("change", function (event) {
            var val = $("#ProjectId option:selected").val();
            if (val=="") {
                return;
            }
        $.ajax({
            url: "@Url.Action("GetMilestoneByProjectId", "Milestone")",
            data: {id:val},
            type: 'GET',
            cache: false,
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            success: function (result) {
                if (result.status) {
                    var dbSelect = $('#MilestoneId');
                    dbSelect.empty();
                    dbSelect.append("<option value=''>Select an option</option>");

                    //dbSelect.select2('data', null);

                    //$("#select_with_data").html('').trigger('change');//.select2({
                    //    data: result.DataList
                    //});
                    $.each(result.dataList, function (key, value) {
                        dbSelect.append("<option value='" + value.id + "'>" + value.text + "</option>");

                    });

                    dbSelect.trigger('change');
                }

            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(thrownError);
            }
        });
    });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

SunbiHR/Views/Report/Index.cshtml
@model IEnumerable<SunbiHR.Models.Entity.EmployeeInfo.EmployeeDailyReport>

@{
    ViewData["Title"] = "Daily Reports";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var ReportViewModel = new SunbiHR.ViewModel.ReportViewModel()
    {
        Title = "Daily Report",
        CreatedOn = DateTime.Now
    };
}
<section>
    <div class="flex-lg-row-reverse row">
        <div class="float-right">
            <a class="p-4" data-toggle="collapse" href="#search" role="button" aria-expanded="false" aria-controls="search">
                Search
            </a>
            <a class="p-4" data-toggle="modal" data-target="#report" asp-action="Create">+ Add Daily Report</a>
            <div class="modal fade" id="report" tabindex="-1" role="dialog" aria-labelledby="report-label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="reportTitle"> Daily Report</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form asp-action="Create">
                                @Html.EditorFor(x => ReportViewModel)
                            </form>
                        </div>
                        @*<div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Save</button>
                            </div>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="collapse row" id="search">
        <div class="card card-body">
            <form asp-action="Index">
                <div class="form-row">
                    <div class="col-md-6 form-group">
                        <label>From Date</label>
                        <input type="text" name="fromDate" class="form-control datepicker" value='@ViewData["fromDate"]' />
                    </div>
                    <div class="col-md-6 form-group">
                        <label>To Date</label>
                        <input type="text" name="toDate" class="form-control datepicker" value='@ViewData["toDate"]' />
                    </div>
                </div>
                <div class="row">
                    @if (User.IsInRole("Administrator"))
                    {
                        <div class="col-md-6 form-group">
                            <label>Employee</label>
                            <div>
                                <select name="EmployeeId" asp-items="ViewBag.EmployeeId" class="form-control search-select">
                                    <option value="">Select All</option>
                                </select>
                            </div>
                        </div>

                    }
                    <div class="col-md-6 form-group p-4">
                        <button class="btn btn-success"
                                type="submit">
                            Reports
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<section id="team" class="pb-5">
    <div class="container">
        <h5 class="section-title h1">Daily Reports</h5>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-bordered table-striped dataTable w-100">
                    <thead>
                        <tr>
                            <th>#</th>
                            @*<th>@Html.DisplayNameFor(x => x.CreatedOn)</th>*@
                            <th>Submitted Date</th>
                            @if (User.IsAdmin())
                            {
                                <th>@*@Html.DisplayNameFor(x => x.EmployeeId)*@ Employee Name</th>

                            }
                            <th>@Html.DisplayNameFor(x => x.Title)</th>

                            <th>@Html.DisplayNameFor(x => x.Description)</th>
                            @if (User.IsAdmin())
                            {
                                <th></th>
                            }

                        </tr>
                    </thead>
                    <tbody>
                        @{ var i = 1;}
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@i</td>
                                <td>@(item.CreatedOn.ToString("yyyy-MM-dd"))</td>
                                @if (User.IsAdmin())
                                {
                                    <td>@Html.DisplayFor(x => item.EmployeeInformation.Fullname)</td>
                                }
                                <td>@Html.DisplayFor(model => item.Title)</td>
                                <td>@Html.DisplayFor(model => item.Description)</td>
                                @if (User.IsAdmin())
                                {
                                    <td>
                                        <a asp-action="Details" asp-controller="Report" asp-route-id="@item.Id" title="Detailsd">
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                }
                            </tr>
                            i++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}