SunbiHR/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Asn1.Cms;
using SunbiHR.DBContext;
using SunbiHR.Extensions;
using SunbiHR.Helper;
using SunbiHR.Helper.Mail;
using SunbiHR.Models.Entity;
using SunbiHR.Models.Entity.ProjectInfo;
using SunbiHR.Models.Entity.TaskInfo;
using SunbiHR.Models.Entity.UserDetails;
using SunbiHR.Models.Enum;
using SunbiHR.ViewModel;
using SunbiHR.ViewModel.Mail;
using static SunbiHR.Models.Enum.TaskEnums;

namespace SunbiHR.Controllers
{
    [Authorize(Roles ="Administrator,SuperAdmin")]
    public class TaskController : Controller
    {
        private readonly SunbiDBContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ILogger<TaskController> _logger;
        private readonly IMailService _mailService;

        public TaskController(
            SunbiDBContext context,
            UserManager<ApplicationUser> userManager,
            ILogger<TaskController> logger,
            IMailService mailService)
        {
            _context = context;
            this.userManager = userManager;
            _logger = logger;
            _mailService = mailService;
        }

        // GET: Task
        public async Task<IActionResult> Index()
        {

            var taskInformationList = _context.TaskInformation
                .Where(x => x.Deleted_Status == false)
                .Include(e => e.ApplicationUser)
                .Include(x => x.ProjectInformation)
                .Include(x => x.Milestone)
                .Where(x => x.CreatedById == userManager.GetUserId(User));
            return View(await taskInformationList.ToListAsync());
        }

        // GET: Task/Details/5
        [AllowAnonymous]
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskInformation = await _context.TaskInformation
                .Include(e => e.ApplicationUser)
                .Include(x => x.ProjectInformation)
                .Include(x => x.Milestone)
                .Include(x => x.TaskEmployee)
                .ThenInclude(x => x.EmployeeInformation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (taskInformation == null)
            {
                return NotFound();
            }
            return View(taskInformation);
        }

        public IActionResult Create()
        {
            var taskViewModel = new TaskViewModel();
            InitCommon(taskViewModel);
            return View(taskViewModel);
        }

        private void InitCommon(TaskViewModel taskViewModel)
        {
            ViewData["ProjectId"] = new SelectList(_context.ProjectInformation, "Id", "Title", taskViewModel?.ProjectId);
            ViewData["EmployeeIds"] = new MultiSelectList(_context.EmployeeInformation, "Id", "Fullname", taskViewModel?.TaskEmployee?.Select(x => x.EmployeeId).ToArray());
            var milestoneListByProjectId = new List<Milestone>();
            if (taskViewModel?.ProjectId != null)
            {
                milestoneListByProjectId = _context.Milestone.Where(x => x.Deleted_Status == false && x.ProjectId == taskViewModel.ProjectId).ToList();
            }

            ViewBag.TaskStatus = new SelectList(Enum.GetValues(typeof(EnumTaskStatus)).Cast<EnumTaskStatus>().Select(v => new SelectListItem
            {
                Text = v.ToString(),
                Value = ((int)v).ToString(),
            }).ToList(), "Value", "Text", taskViewModel?.TaskStatus);
            ViewData["MilestoneId"] = new SelectList(milestoneListByProjectId, "Id", "Title", taskViewModel?.MilestoneId);
        }

        // POST: Task/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrUpdate(TaskViewModel taskViewModel)
        {
            try
            {

                if (string.IsNullOrEmpty(taskViewModel.Id))
                {
                    var taskInformation = new TaskInformation();

                    taskInformation.CreatedById = User.GetUserId();
                    taskInformation.CreatedOn = DateTime.Now;
                    taskInformation.LastModifiedDate = DateTime.Now;
                    taskInformation.ModifiedTimes = 0;
                    taskInformation.Record_Status = Models.Enum.Record_Status.Active;
                    taskInformation.Deleted_Status = false;
                    SetValuesFromViewModel(taskViewModel, taskInformation);
                    taskInformation.Id = Guid.NewGuid().ToString();

                    _context.Add(taskInformation);

                    await _context.CommitAsync();
                    await SendMailToAssignedEmployee(taskViewModel);
                    return Json(new { status = true, msg = "Task Created Successfully" });
                }
                else
                {
                    var OldData = await _context.TaskInformation.Include(x => x.TaskEmployee)
                   .FirstOrDefaultAsync(x => x.Id == taskViewModel.Id);
                    if (OldData == null)
                    {
                        return Json(new { status = false, msg = "Data Not found." });
                    }
                    OldData.LastModifiedDate = DateTime.Now;
                    OldData.ModifiedTimes += 1;
                    SetValuesFromViewModel(taskViewModel, OldData);
                    _context.Update(OldData);

                    await _context.CommitAsync();
                    await SendMailToAssignedEmployee(taskViewModel);

                    return Json(new { status = true, msg = "Task Updated Successfully" });
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ExceptionHelper.GetMsg(ex));
                return Json(new { status = false, msg = ExceptionHelper.GetMsg(ex) });

            }

        }

        private async Task SendMailToAssignedEmployee(TaskViewModel taskViewModel)
        {
            var AssignedEmployeeEmail = _context.EmployeeInformation.Where(x => taskViewModel.EmployeeIds.Contains(x.Id)).Select(x => x.Email).ToArray();
            var duedateHaveValue = taskViewModel.DueDate.HasValue ? (" with due date" + taskViewModel.DueDate.Value.ToString("yyyy-MM-dd")) : "";
            var msg = "";
            foreach (var item in AssignedEmployeeEmail)
            {
                try
                {
                    var mailRequest = new MailRequest
                    {
                        Subject = "New Task has been Assigned",
                        Body = $"<h3>Dear User,</h3><p>New Task { taskViewModel.Title} has been assigned to you{ duedateHaveValue} .</p>",
                        ToEmail = item
                    };
                    await _mailService.SendEmailAsync(mailRequest);
                }
                catch (Exception ex)
                {
                    msg = "Error while sending mail" + ExceptionHelper.GetMsg(ex);
                    _logger.LogError(ex, "Error while sending task assigned mail.");
                }
            }
        }

        public async Task<ActionResult> AjaxTaskList(string id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Id is null");
                }

                var taskList = await _context.TaskInformation
                    .Include(e => e.ApplicationUser)
                    .Include(x => x.ProjectInformation)
                    .Where(m => m.Deleted_Status == false && m.ProjectId == id).
                   ToListAsync();
                return PartialView(taskList);

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching taskdata");
            }
            return PartialView(new List<TaskInformation>());

        }
        public async Task<ActionResult> AjaxActiveTaskList(string id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Id is null");
                }

                var taskList = await _context.TaskInformation
                    .Include(e => e.ApplicationUser)
                    .Include(x => x.ProjectInformation)
                    .Where(m => m.Deleted_Status == false && m.ProjectId == id && m.TaskStatus==EnumTaskStatus.Open)
                    .ToListAsync();
                return PartialView(taskList);

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching taskdata");
            }
            return PartialView(new List<TaskInformation>());

        }

        // POST: Task/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TaskViewModel taskViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var taskInformation = new TaskInformation();
                    SetValuesFromViewModel(taskViewModel, taskInformation);
                    taskInformation.Id = Guid.NewGuid().ToString();
                    taskInformation.CreatedById = User.GetUserId();

SunbiHR/Views/Project/Create.cshtml
@model SunbiHR.ViewModel.ProjectViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>ProjectInformation</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            @Html.EditorForModel()
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

SunbiHR/Views/Project/Delete.cshtml
@model SunbiHR.Models.Entity.ProjectInfo.ProjectInformation

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectInformation</h4>
    <hr />
    @Html.DisplayForModel()

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SunbiHR/Views/Project/Details.cshtml
@model SunbiHR.Models.Entity.ProjectInfo.ProjectInformation

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var projectViewModel = new ProjectViewModel()
    {
        Id = Model.Id,
        Description = Model.Description,
        EmployeeProjects = Model.EmployeeProjects,
        Title = Model.Title,
        StartedDate = Model.StartedDate,
        EstimatedEndDate = Model.EstimatedEndDate
    };
}

<h1>Details</h1>

<div>
    <h4>ProjectInformation</h4>
    <hr />
    @*@Html.DisplayForModel()*@
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
    <div class="modal fade" id="editMilestone" tabindex="-1" role="dialog" aria-labelledby="editMilestone-label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editMilestoneTitle">Add Milestone</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @{
                        var MilestoneViewModel = new MilestoneViewModel()
                        {
                            ProjectId = Model.Id,
                            ProjectInformation = Model
                        };
                    }
                    <form asp-action="Create" asp-controller="Milestone" class="ajaxSubmit" method="post" data-refresh=".milestoneList">
                        @*@Html.HiddenFor(x => x.Id)*@
                        @Html.EditorFor(x => MilestoneViewModel)
                    </form>
                </div>
                @*<div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save</button>
                    </div>*@
            </div>
        </div>
    </div>
    <div class="modal fade" id="editTask" tabindex="-1" role="dialog" aria-labelledby="editTask-label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editTaskTitle">Add Task</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @{
                        var TaskViewModel = new TaskViewModel()
                        {
                            ProjectId = Model.Id,
                            ProjectInformation = Model
                        };
                    }
                    <form asp-action="CreateOrUpdate" asp-controller="Task" class="ajaxSubmit" method="post" data-refresh=".taskList">
                        @*@Html.HiddenFor(x => x.Id)*@
                        @Html.EditorFor(x => TaskViewModel)
                    </form>
                </div>

            </div>
        </div>
    </div>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="project-tab" data-toggle="tab" href="#project" role="tab" aria-controls="project" aria-selected="true">
                Overview
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="milestone-tab" data-toggle="tab" href="#milestone" role="tab" aria-controls="milestone" aria-selected="false">
                Milestone
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="task-tab" data-toggle="tab" href="#task" role="tab" aria-controls="task" aria-selected="false">
                Task
            </a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="project" role="tabpanel" aria-labelledby="project-tab">
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="card-body">
                        <h5 class="card-title">Milestone</h5>

                        <div class="milestoneList" data-url="@Url.Action("AjaxMilestoneList","MileStone",new { id=Model.Id})">
                            @{await Html.RenderPartialAsync("Partial/_MilestoneList", Model.Milestone);}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="card-body">
                        <h5 class="card-title">Active Tasks</h5>

                        @*<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>*@
                        <div class="taskList" data-url="@Url.Action("AjaxActiveTaskList","Task",new { id=Model.Id})">
                            @{await Html.RenderPartialAsync("Partial/_TaskList", Model.TaskInformation.Where(x => x.TaskStatus == SunbiHR.Models.Enum.TaskEnums.EnumTaskStatus.Open).AsEnumerable());}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="milestone" role="tabpanel" aria-labelledby="milestone-tab">

            @*//Project Details*@
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="card-body">
                        <h5 class="card-title">Milestone</h5>
                        <a class="btn btn-success text-white" data-toggle="modal" data-target="#editMilestone">Add Milestone</a>

                        <div class="milestoneList" data-url="@Url.Action("AjaxMilestoneList","MileStone",new { id=Model.Id})">
                            @{await Html.RenderPartialAsync("Partial/_MilestoneList", Model.Milestone);}
                        </div>

                    </div>
                </div>
            </div>
            @*//add milestone
                //view and edit or add task related to milestone*@

        </div>
        <div class="tab-pane fade" id="task" role="tabpanel" aria-labelledby="task-tab">
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="card-body">
                        <h5 class="card-title">Tasks</h5>
                        <a class="btn btn-success text-white" data-toggle="modal" data-target="#editTask">Add Task</a>
                        <div class="taskList" data-url="@Url.Action("AjaxTaskList","Task",new { id=Model.Id})">
                            @{await Html.RenderPartialAsync("Partial/_TaskList", Model.TaskInformation);}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

SunbiHR/Views/Project/Edit.cshtml
@model SunbiHR.ViewModel.ProjectViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>ProjectInformation</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            @Html.EditorForModel()
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

SunbiHR/Views/Project/Index.cshtml
@model IEnumerable<SunbiHR.Models.Entity.ProjectInfo.ProjectInformation>

@{
    ViewData["Title"] = "Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section>
    <p class="float-right">
        <a asp-action="Create">+ Add an Project</a>
    </p>

</section>

<section id="team" class="pb-5">
    <div class="container">
        <h5 class="section-title h1">Projects</h5>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-xs-12 col-sm-6 col-md-4">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title text-center">@item.Title</h5>
                            <p class="card-text text-center">@item.Description</p>
                            @if (item.EmployeeProjects != null && item.EmployeeProjects.Any())
                            {
                                <div>
                                    <div class="text-center">
                                        <label class="font-weight-bold"> Employees</label>
                                    </div>
                                    @foreach (var EmployeeProjects in item.EmployeeProjects)
                                    {
                                        <div class="">
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <p><img class=" img-fluid card-img p-1" src="~/Images/usr.png" alt="card image"></p>
                                                    </div>
                                                    <div class="col-9">
                                                        <div class="card-title">
                                                            <a asp-action="Details" asp-controller="Employee" asp-route-id="@EmployeeProjects.EmployeeInformation.Id">@EmployeeProjects.EmployeeInformation.Fullname</a>
                                                        </div>
                                                        <p class="card-text">@EmployeeProjects.EmployeeInformation.Position</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        //<span class="badge badge-success">@EmployeeProjects.EmployeeInformation.Fullname</span>
                                    }
                                </div>
                            }
                            <br />
                            <div class="text-center">
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</section>
@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}